pipeline:
  type: PIPELINE
  resolution: 2
  pipeline:
    source:
      type: SAMPLER
      biomes: AQUA_PLAINS
      sampler:
        type: CONSTANT
    stages:
      - type: REPLACE
        from: AQUA_PLAINS
        to: YELLOW_PLAINS
        sampler:
          type: EXPRESSION
          expression: noise(x, z) > 0
          samplers:
            noise:
              dimensions: 2
              type: OPEN_SIMPLEX_2
              frequency: 0.005
